.. fillintheblank:: return_main_2
    :author: bmiller
    :difficulty: 3
    :basecourse: thinkcpp
    :topic: Chapter5/returningfrommain
    :from_source: T

    Usually, we return |blank| to exit main.  However, if there are
    any errors that we catch, we might return |blank|.

    - :[0]: Correct!
      :x: Try again!
    - :-1: Correct!
      :.*: Try again!